/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formulario;

import javax.swing.JOptionPane;

/**
 *
 * @author jerry
 */
public class JFrm_Conversor extends javax.swing.JFrame {

    /**
     * Creates new form JFrm_Conversor
     */
    
     private String[] origen ={"","Lempiras","Dolar","Euros"};
     private String[] destino ={"","Lempiras","Dolar","Euros"};
     
    public JFrm_Conversor() {
        initComponents();
        cargar_cboorigen();
        cargar_cbodestino();
    }
    
    
       public void cargar_cboorigen(){
    
        int i=0;
        
        for(i=0;i<this.origen.length;i++)
     
            
            this.cboorigen.addItem(origen[i]);
    }
       
       
       public void cargar_cbodestino(){
       
            int a=0;
        
        for(a=0;a<this.destino.length;a++)
     
            
            this.cbodestino.addItem(destino[a]);
       
       }
       
        public void funcion(){
 
      String tt;
      int ori,dest;
      double total,lp,canti;
      
      canti=Double.parseDouble(cantidad.getText());
       
     
     ori=this.cboorigen.getSelectedIndex();
     dest=this.cbodestino.getSelectedIndex();
     
      if (ori==1 && dest==1){
     
        JOptionPane.showMessageDialog(this,"No se puede realizar la conversion");
      }
        else if (ori==2 && dest==2){
     
        JOptionPane.showMessageDialog(this,"No se puede realizar la conversion");
     }
         else if (ori==3 && dest==3){
     
        JOptionPane.showMessageDialog(this,"No se puede realizar la conversion");
     }
     
         else if (ori==1 && dest==2){
     
        total=canti*0.040; 
     
        tt=Double.toString(total);
        
        ttt.setText(tt);
     }
      
         else if (ori==1 && dest==3){
     
        total=canti*0.034; 
     
        tt=Double.toString(total);
        
        ttt.setText(tt);
     }
       else if (ori==2 && dest==1){
     
        total=canti*24.94; 
     
        tt=Double.toString(total);
        
        ttt.setText(tt);
     } 
       else if (ori==2 && dest==3){
     
        total=canti*0.86; 
     
        tt=Double.toString(total);
        
        ttt.setText(tt);
     }
      else if (ori==3 && dest==1){
     
        total=canti*29.01; 
     
        tt=Double.toString(total);
        
        ttt.setText(tt);
     }
      else if (ori==3 && dest==2){
     
        total=canti*1.16; 
     
        tt=Double.toString(total);
        
        ttt.setText(tt);
     }
      
     
     
 }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cboorigen = new javax.swing.JComboBox<>();
        cbodestino = new javax.swing.JComboBox<>();
        cantidad = new javax.swing.JTextField();
        ttt = new javax.swing.JLabel();
        jbtncalcular = new javax.swing.JButton();
        label2 = new java.awt.Label();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        s = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cboorigen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboorigenActionPerformed(evt);
            }
        });

        cbodestino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbodestinoActionPerformed(evt);
            }
        });

        ttt.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        ttt.setText("0");

        jbtncalcular.setText("CALCULAR");
        jbtncalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtncalcularActionPerformed(evt);
            }
        });

        label2.setAlignment(java.awt.Label.CENTER);
        label2.setBackground(new java.awt.Color(10, 10, 10));
        label2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        label2.setEnabled(false);
        label2.setFont(new java.awt.Font("Edwardian Script ITC", 3, 60)); // NOI18N
        label2.setForeground(new java.awt.Color(255, 153, 0));
        label2.setMaximumSize(new java.awt.Dimension(0, 0));
        label2.setMinimumSize(new java.awt.Dimension(459, 52));
        label2.setText("CONVERSOR DE MONEDA");

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel1.setText("CANTIDAD");

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel2.setText("MONEDA INICIAL");

        jLabel3.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel3.setText("MONEDA  FINAL");

        jLabel4.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel4.setText("TOTAL");

        s.setText("SALIR");
        s.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label2, javax.swing.GroupLayout.DEFAULT_SIZE, 894, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbodestino, 0, 235, Short.MAX_VALUE)
                    .addComponent(cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboorigen, 0, 235, Short.MAX_VALUE)
                    .addComponent(ttt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(s, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtncalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(label2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(cboorigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(cbodestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(72, 72, 72)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(ttt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtncalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(s, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cboorigenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboorigenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboorigenActionPerformed

    private void cbodestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbodestinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbodestinoActionPerformed

    private void jbtncalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtncalcularActionPerformed
        // TODO add your handling code here:
        
        funcion();
    }//GEN-LAST:event_jbtncalcularActionPerformed

    private void sActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_sActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrm_Conversor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrm_Conversor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrm_Conversor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrm_Conversor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrm_Conversor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cantidad;
    private javax.swing.JComboBox<String> cbodestino;
    private javax.swing.JComboBox<String> cboorigen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton jbtncalcular;
    private java.awt.Label label2;
    private javax.swing.JButton s;
    private javax.swing.JLabel ttt;
    // End of variables declaration//GEN-END:variables
}
